<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="robots" content="noindex, nofolllow, noarchive, noodp, NoImageIndex, noydir">
    <title>Firefly III</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <base href="{{ route('index') }}/">
    <link rel="stylesheet" href="lib/bootstrap/css/bootstrap.min.css" type="text/css" media="all"/>
    <link rel="stylesheet" href="lib/font-awesome/css/font-awesome.min.css" type="text/css" media="all"/>
    <link href="lib/adminlte/css/AdminLTE.min.css" rel="stylesheet" type="text/css"/>
    <link href="css/firefly.css" rel="stylesheet" type="text/css"/>

    <!-- favicons -->
    {% include('partials/favicons') %}

</head>
<body class="ff-error-page">
<div class="ff-error-box">
    <div class="login-logo">
        <a href="{{ route('index') }}"><b>Firefly</b>III</a>
    </div>

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <h3 class="text-info">Whoops! An error occurred.</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <p>
                Unfortunately, this error was not recoverable. Firefly III broke. The error is:
            </p>
            <p class="text-danger">
                {{ exception.getMessage |default('General unknown errror') }}
            </p>
        </div>
    </div>
</div>

{% if debug %}
    <div class="error-stack">
        <h4>Error</h4>
        <p>This error occured in file <span style="font-family: monospace;">{{ exception.getFile }}</span> on line {{ exception.getLine }} with
            code {{ exception.getCode }}.</p>
        <h4>Stack trace</h4>
        <div style="font-family: monospace;font-size:11px;">
            {{ exception.getTraceAsString|nl2br }}
        </div>
    </div>
{% endif %}
</body>
</html>
